[package]
name = "carta"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.23.2", features = ["v4"] }
mockall = "0.14"
async-trait = "0.1.89"
tonic = "0.14.4"
tokio = { version = "1.52.3", features = ["full"] }
prost = "0.14.4"
tonic-build = "0.14.6"
tonic-prost = "0.14.6"
sqlx = { version = "0.9.0", features = [
  "postgres",
  "migrate",
  "runtime-tokio",
  "uuid",
] }
dotenvy = "0.15.7"
argon2 = "0.6.0-rc.8"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }

[build-dependencies]
tonic-prost-build = "0.14.6"
